---
- name: Update apt cache
  apt: >
    update_cache=yes
    cache_valid_time={{ apt_cache_valid_time|default(3600) }}

- name: Install essential packages
  apt: >
    name={{ item }}
    state=installed
  with_items:
    - python-apt
    - apt-transport-https

- name: Register that this role has run
  set_fact: apt_has_run=true
  when: apt_has_run is not defined
